version: '3.7'

services:
  
  router:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./default:/etc/nginx/conf.d/default.conf
    mem_limit: 200m

  app:
    image: php:8.1-apache-buster
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_URL=http://172.17.0.1:9000
      #- AWS_USE_PATH_STYLE_ENDPOINT=
    volumes:
      - ./:/var/www/html
    mem_limit: 1G
